### ISSUE TITLE
Loading environment error (Trade::AbstractImporter::image2D(): index out of range)

### ISSUE THREAD

**Issue by rohjunha** [facebookresearch/exploring_exploration#6]
I have been followed the instruction to setup `habitat_sim` and `habitat_api` with specific commits.
However, whenever I tried to use `habitat_api`, I got an error below:

```
(...)
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_KHR_debug
Using driver workarounds:
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
Trade::AbstractImporter::image2D(): index out of range
Aborted (core dumped)
```

While I did not get the error with recent versions of `habitat_sim` and `habitat_api`, I could not use the code in this repository.

**Comment by srama2512** [comment]
Hi @rohjunha,

I would recommend checking this with the habitat-sim team to see if they have a solution. Make sure to mention the right version (with commit it).

**Comment by srama2512** [comment]
Based on conversations with the habitat team, this error arises from trying to load basis compressed MP3D scenes using older habitat versions. Using the original MP3D scenes should fix the issue.

**Comment by GaganBhat** [comment]
@srama2512 Where can we get the MP3D scenes that are not load basis compressed? Having the same `index out of range` core dump.

**Comment by srama2512** [comment]
@GaganBhat  I haven't downloaded it a while, but it should be accessible from the MP3D website here: https://niessner.github.io/Matterport/. You can reach out to them in case the link is not available.

**Comment by GaganBhat** [comment]
@srama2512 

Downloading using the default script they give after approval now still results in this issue. 

I'm assuming this means they have updated MP3D to include basis compressed scenes, which is causing this issue because we use an older habitat-sim and API for this project. 

I see two ways to approach this: 

1. I work with the MP3D authors to get an older version of their data
2. We find out where this issue is stemming from (either habitat-sim or habitat-lab/habitat-api), and selectively upgrade it to make it compatible with the latest data. 

Would appreciate if you can give any pointers in either direction!

**Comment by GaganBhat** [comment]
Solved the issue. 

In order to get the old MP3D dataset without the compression, a small change needs to be made to the `download_mp.py` script that you receive once you've agreed to the T&C. 

Replace the `'habitat': 'mp3d_habitat.zip'` task mapping with  `'habitat': 'mp3d_habitat.v0.zip'`. 

Run the script like so `python2 download_mp.py --task habitat -o data/scene_datasets/mp3d/` inside the `habitat-api` folder. 

Then make sure to extract the contents of the task zip in under scene_datasets where the script expects it.

**Comment by srama2512** [comment]
Thanks for the update, @GaganBhat!
